stages:
  - build
  - test
  - deploy
  - build production

default:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind

build:
  stage: build
  variables:
    BUILDPLATFORM: linux/amd64
    BUILDARCH: amd64
  interruptible: true
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull "$REGISTRY_DOMAIN/chrisleekr/multicloud-k8s-iac:cache" || true
    - >
      docker buildx build . --pull
      --cache-from=$REGISTRY_DOMAIN/chrisleekr/multicloud-k8s-iac:cache
      --progress plain -t
      $REGISTRY_DOMAIN/chrisleekr/multicloud-k8s-iac:build-$CI_COMMIT_SHORT_SHA
      -t $REGISTRY_DOMAIN/chrisleekr/multicloud-k8s-iac:cache
    - docker push $REGISTRY_DOMAIN/chrisleekr/multicloud-k8s-iac:cache
    - docker push
      $REGISTRY_DOMAIN/chrisleekr/multicloud-k8s-iac:build-$CI_COMMIT_SHORT_SHA

lint-helm:
  stage: test
  image: $REGISTRY_DOMAIN/chrisleekr/multicloud-k8s-iac:build-$CI_COMMIT_SHORT_SHA
  interruptible: true
  artifacts:
    paths:
      - helm/nvm/template
      - helm/nvm-db/template
    expire_in: '7 days'
  script:
    - ./scripts/validate-helm.sh

lint-terraform:
  stage: test
  image: $REGISTRY_DOMAIN/chrisleekr/multicloud-k8s-iac:build-$CI_COMMIT_SHORT_SHA
  interruptible: true
  script:
    - ./scripts/validate-terraform.sh

production:
  stage: build production
  only:
    - master
  before_script:
    - apk add curl git jq
    - mkdir -p ~/.docker/cli-plugins/
    - BUILDX_LATEST_BIN_URI=$(curl -s -L
      https://api.github.com/repos/docker/buildx/releases/latest | jq
      --raw-output '.assets[] | select(.name | contains ("linux-amd64")) |
      .browser_download_url')
    - curl -s -L ${BUILDX_LATEST_BIN_URI} -o ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create dind
    - docker buildx create --driver docker-container --use dind
  script:
    - docker buildx build --progress plain --platform
      linux/amd64,linux/arm64 --pull --tag
      $REGISTRY_DOMAIN/chrisleekr/multicloud-k8s-iac:latest --push .
