---
# Refer: https://github.com/techtales-io/terraform-minio/blob/main/.pre-commit-config.yaml
fail_fast: true
default_stages:
  - pre-commit
  - pre-push

repos:
  - repo: "https://github.com/hadolint/hadolint"
    rev: "v2.12.0"
    hooks:
      - id: "hadolint"
        name: "Lint Dockerfiles"
        types:
          - "dockerfile"
        args:
          - "--no-color"
          - "--strict-labels"

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
      - id: shellcheck

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: "^[^/]+$"
      - id: terraform_trivy
        args:
          - --args=--config=__GIT_WORKING_DIR__/.trivyignore.yaml
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Prevent giant files from being committed. default=500kB
      - id: check-added-large-files
      # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-case-conflict
      # Attempts to load all json files to verify syntax.
      - id: check-json
      # Checks for symlinks which do not point to anything.
      - id: check-symlinks
      # Checks for the existence of private keys.
      - id: detect-private-key
      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer
      # Removes UTF-8 byte order marker
      - id: fix-byte-order-marker
      # Replaces or checks mixed line ending.
      - id: mixed-line-ending
        args:
          - --fix=auto
      # trailing-whitespace
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      # Protect specific branches from direct checkins.
      - id: no-commit-to-branch
        args: ["--branch", "main"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.20.0
    hooks:
      - id: gitleaks
        stages: [pre-commit]
