version: "3"

dotenv: [".env"]

env:
  IMAGE_TAG:
    sh: "echo ${IMAGE_TAG:-latest}"
  REGISTRY_DOMAIN:
    sh: "echo ${REGISTRY_DOMAIN:-registry.hub.docker.com}"
  REPO_NAME:
    sh: "echo ${REPO_NAME:-chrisleekr}"
  IMAGE_NAME:
    sh: "echo ${IMAGE_NAME:-multicloud-k8s-iac}"
  BUILD_PLATFORM:
    sh: "echo ${BUILD_PLATFORM:-linux/amd64}" # Align with the GitLab CI
  BUILD_ARCH:
    sh: "echo ${BUILD_ARCH:-amd64}" # Align with the GitLab CI
  ENVIRONMENT:
    sh: "echo ${ENVIRONMENT:-dev}"
  REGION:
    sh: "echo ${REGION:-ap-southeast-2}"

tasks:
  setup:repo:
    desc: Setup the repository
    cmds:
      - pre-commit install

  precommit:
    desc: Run pre-commit hooks
    cmds:
      - pre-commit run --all-files  --verbose

  validate:helm:
    desc: Validate Helm
    cmds:
      - ./scripts/validate-helm.sh

  validate:terraform:
    desc: Validate Terraform
    cmds:
      - ./scripts/validate-terraform.sh

  docker:build:
    desc: Build Docker image
    cmds:
      - ./scripts/docker-build.sh

  docker:run:
    desc: Run Docker container
    cmds:
      - ./scripts/docker-run.sh

  docker:shell:
    desc: Access to docker shell
    cmds:
      - docker exec -it "${IMAGE_NAME}" /bin/bash

  docker:exec:
    desc: Execute docker command
    cmds:
      - task docker-run
      - task docker-shell

  aws:cloudformation:validate:
    desc: Validate AWS CloudFormation
    cmds:
      - ./workspaces/aws/cloudformation/cloudformation-validate.sh

  aws:cloudformation:deploy:
    desc: Deploy AWS CloudFormation
    cmds:
      - ./workspaces/aws/cloudformation/cloudformation-deploy.sh

  aws:terraform:init:
    desc: Initialize AWS Terraform
    dir: workspaces/aws/terraform
    cmds:
      - terraform init

  aws:terraform:validate:
    desc: Validate AWS Terraform
    dir: workspaces/aws/terraform
    cmds:
      - terraform validate

  aws:terraform:plan:
    desc: Plan AWS Terraform
    dir: workspaces/aws/terraform
    cmds:
      - terraform plan

  aws:terraform:apply:
    desc: Apply AWS Terraform
    dir: workspaces/aws/terraform
    cmds:
      - terraform apply

  aws:bastion:access:
    desc: Access to AWS Bastion
    cmds:
      - ./workspaces/aws/scripts/access-bastion.sh

  gcp:terraform:init:
    desc: Initialize GCP Terraform
    dir: workspaces/gcp/terraform
    cmds:
      - terraform init

  gcp:terraform:validate:
    desc: Validate GCP Terraform
    dir: workspaces/gcp/terraform
    cmds:
      - terraform validate

  gcp:terraform:plan:
    desc: Plan GCP Terraform
    dir: workspaces/gcp/terraform
    cmds:
      - terraform plan

  gcp:terraform:apply:
    desc: Apply GCP Terraform
    dir: workspaces/gcp/terraform
    cmds:
      - terraform apply

  minikube:terraform:init:
    desc: Initialize Minikube Terraform
    dir: workspaces/minikube/terraform
    cmds:
      - terraform init

  minikube:terraform:validate:
    desc: Validate Minikube Terraform
    dir: workspaces/minikube/terraform
    cmds:
      - terraform validate

  minikube:terraform:plan:
    desc: Plan Minikube Terraform
    dir: workspaces/minikube/terraform
    cmds:
      - terraform plan

  minikube:terraform:apply:
    desc: Apply Minikube Terraform
    dir: workspaces/minikube/terraform
    cmds:
      - terraform apply
