{{ range .Values.apps }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if eq $.Values.ingress.className "kong" }}
    konghq.com/preserve-host: "true"
    konghq.com/host-aliases: "{{ $.Values.ingress.host }}"
    # konghq.com/plugins: "correlation-id"
    {{- if .ingress.kong.stripPath }}
    konghq.com/strip-path: "true"
    {{- end }}
    {{- end }}
    {{- if eq $.Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: {{ .ingress.nginx.rewriteTarget }}
    {{- if .ingress.nginx.configurationSnippet }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{ .ingress.nginx.configurationSnippet }}
    {{- end }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    {{- end }}
    {{- if $.Values.ingress.annotations }}
{{- range $key, $value := $.Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
    {{- end }}
  name: ingress-{{.name}}
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ $.Values.ingress.host }}
      secretName: {{ $.Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: "{{ $.Values.ingress.host }}"
      http:
        paths:
          - path: {{ if eq $.Values.ingress.className "nginx" }}{{ .ingress.nginx.path }}{{ else if eq $.Values.ingress.className "kong" }}{{ .ingress.kong.path }}{{ end }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{.name}}
                port:
                  number: {{.containerPort}}
{{ end }}
