{{ range .Values.apps }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .ingress.rewriteTarget }}
    {{- if .ingress.configurationSnippet }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{ .ingress.configurationSnippet }}
    {{- end }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    {{- if $.Values.ingress.annotations }}
{{- range $key, $value := $.Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
    {{- end }}
  name: ingress-{{.name}}
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ $.Values.ingress.host }}
      secretName: {{ $.Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: "{{ $.Values.ingress.host }}"
      http:
        paths:
          - path: {{ .ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{.name}}
                port:
                  number: {{.containerPort}}
{{ end }}
