---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}-secret
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $val.key }}: {{ $val.value | toString | b64enc | quote }}
  {{- end }}
