---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if eq $.Values.ingress.className "kong" }}
    konghq.com/preserve-host: "true"
    konghq.com/host-aliases: "{{ $.Values.ingress.host }}"
    konghq.com/plugins: "correlation-id"
    konghq.com/strip-path: "true"
    konghq.com/path: "/frontend-vue"
    {{- end }}
    {{- if eq $.Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/app-root: /frontend-vue
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    {{- end }}
    {{- if $.Values.ingress.annotations }}
{{- range $key, $value := $.Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
    {{- end }}
  name: ingress-root
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $.Values.ingress.host }}
      secretName: {{ $.Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: "{{ $.Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-vue
                port:
                  number: 80
