name: Lint & Validate
on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        env:
          BUILDPLATFORM: linux/amd64
          BUILDARCH: amd64
        run: |
          docker pull chrisleekr/multicloud-k8s-iac:cache || true
          docker build . \
          --cache-from=chrisleekr/multicloud-k8s-iac:cache \
          -t multicloud-k8s-iac:$GITHUB_SHA \
          -t chrisleekr/multicloud-k8s-iac:cache
          docker push chrisleekr/multicloud-k8s-iac:cache

      - name: Save Docker image
        run: |
          docker save multicloud-k8s-iac:$GITHUB_SHA -o multicloud-k8s-iac-$GITHUB_SHA.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: multicloud-k8s-iac
          path: multicloud-k8s-iac-${{github.sha}}.tar
          if-no-files-found: error
          retention-days: 1

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      # Leave this for future reference
      # - name: Download Docker image
      #   uses: actions/download-artifact@v5
      #   with:
      #     name: multicloud-k8s-iac

      # - name: Load Docker image
      #   run: |
      #     docker load -i multicloud-k8s-iac-$GITHUB_SHA.tar

      - name: Install hadolint
        run: |
          curl -L https://github.com/hadolint/hadolint/releases/download/v2.13.1/hadolint-linux-x86_64 -o hadolint
          chmod +x hadolint
          mv hadolint /usr/local/bin/

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      # - name: Install Helm
      #   uses: azure/setup-helm@v4.3.1

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
